version: '2.1'
services: 
   ascent-demo-service:
    image: ascent-demo-service
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    external_links: 
      - ascent-config
      - ascent-discovery
      - ascent-amqp
      - ascent-zipkin
    volumes:
      - ~/logs:/logs
    networks:
      - ascent_ascentnet
networks: 
  ascent_ascentnet: 
    external: true