version: '3'
services: 
   ascent-demo-service:
    image: ascent/ascent-demo-service
    environment:
      - SPRING_PROFILES_ACTIVE=aws-prod
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
      - ascentnet
   ascent-document-service:
    image: ascent/ascent-document-service
    environment:
      - SPRING_PROFILES_ACTIVE=aws-prod
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
      - ascentnet
networks: 
 ascentnet: 
    external:
      name: ascent_ascentnet

