version: '3'
services: 
   ascent-demo-service:
    image: ascent/ascent-demo-service
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    networks:
      - ascentnet
   ascent-document-service:
    image: ascent/ascent-document-service
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    networks:
      - ascentnet
networks: 
 ascentnet: 
    external:
      name: ascent_ascentnet

