version: '3'
services:
  ascent-amqp:
    image: rabbitmq
    hostname: ascent-amqp
    networks:
    - ascentnet
  ascent-discovery:
    image: ascent/ascent-discovery
    hostname: ascent-discovery
    ports:
    - 8761
    environment:
    - SPRING_PROFILES_ACTIVE=aws-ci
    - VAULT_ADDR=${VAULT_ADDR}
    - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
    - ascentnet
  ascent-config:
    image: ascent/ascent-config
    ports:
    - 8760
    environment:
    - SPRING_PROFILES_ACTIVE=aws-ci
    - VAULT_ADDR=https://${VAULT_HOST}:8200
    - VAULT_TOKEN=${VAULT_TOKEN}
    - VAULT_HOST=${VAULT_HOST}
    - VAULT_SCHEME=https
    networks:
    - ascentnet
  ascent-gateway:
    image: ascent/ascent-gateway
    ports:
    - 8762
    environment:
    - SPRING_PROFILES_ACTIVE=aws-ci
    - VAULT_ADDR=${VAULT_ADDR}
    - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
    - ascentnet
  ascent-dashboard:
    image: ascent/ascent-dashboard
    ports:
    - 8763
    environment:
    - SPRING_PROFILES_ACTIVE=aws-ci
    - VAULT_ADDR=${VAULT_ADDR}
    - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
    - ascentnet
  ascent-zipkin:
    image: ascent/ascent-zipkin
    ports:
    - 8700
    environment:
    - SPRING_PROFILES_ACTIVE=aws-prod
    - VAULT_ADDR=${VAULT_ADDR}
    - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
    - ascentnet
  
networks:
  ascentnet:
    driver: overlay