server:
  port: ${demo-service.server.port:8080}
info:  
  build:
    version:  "@project.version@"
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    
# REDIS (RedisProperties)
redis:
  enabled: false
  cache: 
    defaultExpires: 86400 # (Seconds)
    expires: 
      #Cache Name: TTL (In Seconds)
      demoPersonService: 1800
      demoService: 600
---
spring.profiles: default
spring.cache.type: none

---
spring.profiles: local-int
cache:
    ehcache:
      config: classpath:ehcache.xml   
---
spring: 
  cloud:
    bus:
      enabled: false
#Application Custom Properties          
ascent-demo-service:
  env: default
  propSource: internal
  password: secret
  sampleProperty: >
                  sampleProperty___env/profile:${ascent-demo-service.env}___propSource:
                  ${ascent-demo-service.propSource}__password:${ascent-demo-service.password}
#*********************************************************************
# BGS-Specific SERVICE CLIENT PROPERTIES
#*********************************************************************
---
spring.profiles: default, local-int, docker-demo, aws-ci, aws-dev
spring.profiles.include: remote_client_sims

---
spring.profiles: aws-stage, aws-prod
spring.profiles.include: remote_client_impls
---
#----------------------------------------
# BGS-Specific default properties
#----------------------------------------
bgs:
  url: http://localhost:58540/mockPersonWebServicePortBinding
  username: unitTestUsername
  password: unitTestPassword
  systemId: eBenefits
  vaApplicationName: eBenefits
  vaUCApplicationName: EBENEFITS
  stationId: 281
#---------------------------------------------------
#   PersonService SOAP web service client configuration
#---------------------------------------------------
wss-partner-person: 
  ws:
    client: 
      username: ${bgs.username}
      password: ${bgs.password}
      systemId: {bgs.systemId}
      vaApplicationName: ${bgs.vaApplicationName}
      stationId: ${bgs.stationId}
      endpoint: ${bgs.url}
      methodWarningThreshhold: 2500
      readTimeout: 360000
      connectionTimeout: 120000
#---------------------------------------------------
#   Logging Level for packages
#---------------------------------------------------
logging: 
  level:
    gov:
      va:
        ascent: INFO
    org: 
      springframework: 
        cloud.sleuth.log: INFO
        cloud.sleuth: INFO
        cloud.sleuth.instrument.web: INFO
        security: INFO
        ws: INFO
        cache: INFO
      apache:
        http: 
          impl.client: INFO
    net:
      sf:
        ehcache: INFO
management:
  security:
    enabled: false
#sanitize properties for keys when using /configprops.
endpoints:
  configprops:
    keys-to-sanitize: 'enabled, password'
hystrix:
  command:
    #Property configuration for hystrix command key to monitor async service method
    DemoServiceAsyncReadCommand: 
      execution:
        isolation:
          thread:
            # This property sets the time in milliseconds after which the caller will observe a timeout and 
            # walk away from the command execution. Hystrix marks the HystrixCommand as a TIMEOUT, and performs fallback 
            # logic. Note that there is configuration for turning off timeouts per-command, if that is desired (see command.timeout.enabled).
            # Default Value: 1000
            timeoutInMilliseconds: 6000
    default:
      metrics:
        rollingStats:
          # This property sets the duration of the statistical rolling window, in milliseconds. 
          # This is how long Hystrix keeps metrics for the circuit breaker to use and for publishing 
          # Default Value: 10000
          timeInMilliseconds: 20000
        # This property sets the time to wait, in milliseconds, between allowing health snapshots to be taken that calculate 
        # success and error percentages and affect circuit breaker status. 
        # Default Value: 500
        healthSnapshot: 
          intervalInMilliseconds: 1000
      circuitBreaker:
        # This property sets the amount of time, after tripping the circuit, to reject requests 
        # before allowing attempts again to determine if the circuit should again be closed.
        # Default Value: 5000
        sleepWindowInMilliseconds: 10000
        # This property sets the minimum number of requests in a rolling window that will trip the circuit.
        # Default Value: 20
        requestVolumeThreshold: 4
      execution:
        isolation:
          thread:
            # This property sets the time in milliseconds after which the caller will observe a timeout and 
            # walk away from the command execution. Hystrix marks the HystrixCommand as a TIMEOUT, and performs fallback 
            # logic. Note that there is configuration for turning off timeouts per-command, if that is desired (see command.timeout.enabled).
            # Default Value: 1000
            timeoutInMilliseconds: 5000

# Sleuth configuration     
# To skip specific patterns being exported, added few more customs on top of default skip pattern
# see org.springframework.cloud.sleuth.instrument.web.TraceFilter.DEFAULT_SKIP_PATTERN
spring.sleuth.web.skipPattern: (/api/.*/webjars.*|/api/.*/v2/api-docs.*|/api/.*/swagger-resources.*|/api/.*/swagger-ui.*|/api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/trace|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream)
# comma separated list of matchers
spring.sleuth.rxjava.schedulers.ignoredthreads: HystixMetricPoller,^RxComputation.*$,^RxIoScheduler.*$

#Property configuration to enable or disable JWT security for service calls 
#JWT security is enabled by default in exteral repo. So to disable it you have to
#set the environment system property ascent.security.jwt.enabled=false
ascent:
  security:
    jwt:
      enabled: false
      filter-process-url: /demo/v?/**
  swagger:
    title: Ascent Demo Service v1 API Documentation
    description: API Error Keys <a href="swagger/error-keys.html">error keys</a>
    groupName: demo-v1
    version: ${info.build.version}
    securePaths: /demo.*